language: node_js
node_js: stable
branches:
    only:
    - blog
cache:
    apt: true
    yarn: true
    directories:
    - node_modules
before_install:
- git config --global user.name "ph22"
- git config --global user.email "huangpenghua@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=%HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- hexo clean
- hexo generate
- ls ./node_modules
after_success:
- cd ./public
- cat index.html
- cat ./archives/index.html
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/ph22/ph22.github.io.git
  master
